env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
addons:
  apt:
    update: true
    packages:
    - bash
install: true
before_script: echo "org.gradle.console=auto" > gradle.properties
script:
- bash gradlew -S
- unzip app/build/distributions/app.zip
- bash opt/app/bin/app
- bash opt/app/bin/app ololo trololo
- bash opt/app/bin/app maksimko
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
